language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
install:
  - python setup.py build
  - python setup.py install
  - sudo pip install coveralls
script:
  - sudo PATH=$PATH coverage run setup.py test
after_success:
  coveralls
